"""updated user model

Revision ID: 1285cefe5b86
Revises: 57ed6e153ad6
Create Date: 2024-09-27 23:31:05.837657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1285cefe5b86'
down_revision: Union[str, None] = '57ed6e153ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'hashed_password')
    # ### end Alembic commands ###
