"""create tbl_loans table

Revision ID: 221ae2a99ad1
Revises: 75c41259a02c
Create Date: 2024-10-29 19:48:22.361690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221ae2a99ad1'
down_revision: Union[str, None] = '75c41259a02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_deposits', 'tbl_users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_deposits', type_='foreignkey')
    # ### end Alembic commands ###
