"""Add role column to users table

Revision ID: 4764f6c8f1a6
Revises: eb022174497b
Create Date: 2024-11-25 19:29:30.769054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4764f6c8f1a6'
down_revision: Union[str, None] = 'eb022174497b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('tbl_users', sa.Column('role', sa.String(), nullable=False))
    op.drop_constraint('tbl_deposits_user_id_fkey', 'tbl_deposits', type_='foreignkey')
    op.drop_constraint('uq_tbl_users_user_id', 'tbl_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tbl_users_user_id', 'tbl_users', ['user_id'])
    op.drop_column('tbl_users', 'role')
    # ### end Alembic commands ###
