"""created user table

Revision ID: 57ed6e153ad6
Revises: ddabb2023cc9
Create Date: 2024-09-27 15:49:09.897365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ed6e153ad6'
down_revision: Union[str, None] = 'ddabb2023cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_users_gender'), 'tbl_users', ['gender'], unique=False)
    op.create_index(op.f('ix_tbl_users_id'), 'tbl_users', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_users_name'), 'tbl_users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_name'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_id'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_gender'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
