"""create loan table

Revision ID: 75c41259a02c
Revises: eb022174497b
Create Date: 2024-10-25 13:41:44.079983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

def upgrade():
    # Drop the constraint with CASCADE
    op.execute("ALTER TABLE tbl_users DROP CONSTRAINT uq_tbl_users_user_id CASCADE")
    # Other migration code...
# revision identifiers, used by Alembic.
revision: str = '75c41259a02c'
down_revision: Union[str, None] = 'eb022174497b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  
    # ### commands auto generated by Alembic - please adjust! ###
  #op.drop_constraint('tbl_deposits_user_id_fkey', 'tbl_deposits', type_='foreignkey')
  op.drop_constraint('uq_tbl_users_user_id', 'tbl_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tbl_users_user_id', 'tbl_users', ['user_id'])
    # ### end Alembic commands ###
