"""Add transaction table

Revision ID: c6713752ccca
Revises: 4764f6c8f1a6
Create Date: 2024-11-26 21:54:03.531395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6713752ccca'
down_revision: Union[str, None] = '4764f6c8f1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tbl_deposits', 'tbl_users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_deposits', type_='foreignkey')
    # ### end Alembic commands ###
