"""created deposit table

Revision ID: d7a756c09e27
Revises: 1285cefe5b86
Create Date: 2024-10-22 15:24:16.598290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a756c09e27'
down_revision: Union[str, None] = '1285cefe5b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_tbl_users_id', table_name='tbl_users')
    op.create_index(op.f('ix_tbl_users_user_id'), 'tbl_users', ['user_id'], unique=False)
    op.drop_column('tbl_users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_tbl_users_user_id'), table_name='tbl_users')
    op.create_index('ix_tbl_users_id', 'tbl_users', ['id'], unique=False)
    op.drop_column('tbl_users', 'user_id')
    # ### end Alembic commands ###
